### ISSUE TITLE
60HE design without strap

### ISSUE THREAD

**Issue by bugproof** [WootingKb/wooting-design#2]
Hey how hard would it be to remove the strap on the left? I've never used any CAD software. I tried importing the .stl file into blender and work from there to make left side look like right side but I failed.

What software do you recommend for doing these types of things?

![image](https://user-images.githubusercontent.com/3116731/179877631-ec811394-a2f6-41f5-8e5b-be4c1a55729d.png)

**Comment by PastaJ36** [comment]
It should be doable with a CAD-like software. I think Fusion 360 has a free personal plan. Would recommend to start with the STP file. It includes all the different keyboards parts, you can take out the bottom case from there and modify it. The STL file is not really made for modification, just for producing the file.
